### ISSUE TITLE
Add option to open link directly in browser

### ISSUE THREAD

**Issue by ArunVenkata** [ArunVenkata/ghpr#6]
Add an optional argument such as `-o` which when specified will directly open the link in an available default browser.

We can also explore making this the default behavior in the future.

**Comment by KasunJayasanka** [comment]
Could you please assign me ?

**Comment by ArunVenkata** [comment]
Sure, please provide an update once you have made the proposed changes

**Comment by amankumarhq** [comment]
@ArunVenkata 
I Fixed this issue in #7 
please have a look.
